version: '3'
services:
  backend:
    build: ../../backend/
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: "mongodb://mongo_database"

  mongo_database:
    image: 'mongo'
    container_name: 'warbnb_database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ~/proiect-pw-idp/database/data:/data/db
    ports:
      - '27017-27019:27017-27019'

